### PR TITLE
[BACKLOG-7852] - xmi parser support for level formattter

### PR DESCRIPTION
**Pull request by kurtwalker**

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/olap/OlapHierarchyLevel.java
  src/org/pentaho/metadata/util/XmiParser.java
  test-src/org/pentaho/metadata/XmiParserIT.java

Integration test coverage change:
============
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * Complexity Change :  + 5.26%
 * Instruction Change :  + 2.78%
 * Line Change :  + 3.95%
 * Method Change :  + 6.90%

org.pentaho.metadata.util.XmiParser:
 * Branch Change :  + .07%
 * Complexity Change :  + .11%
 * Instruction Change :  + .03%
 * Line Change :  + .03%

License header violations:
==========================
1. Copyright year is not the current year on src/org/pentaho/metadata/util/XmiParser.java. Found 2009. Was expecting 2016
2. Copyright year is not the current year on test-src/org/pentaho/metadata/XmiParserIT.java. Found 2009. Was expecting 2016

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/src/org/pentaho/metadata/util/XmiParser.java

1. Message: Must have at least one statement. at Line: 930 Column: 45
2. Message: Must have at least one statement. at Line: 987 Column: 101
3. Message: Must have at least one statement. at Line: 1,732 Column: 68
4. Message: Must have at least one statement. at Line: 1,927 Column: 20

File /home/buildguy/project/test-src/org/pentaho/metadata/XmiParserIT.java

1. Message: Using a static member import should be avoided - org.pentaho.metadata.util.Util.validateId. at Line: 23

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/olap/OlapHierarchyLevel.java
  src/org/pentaho/metadata/util/XmiParser.java
  test-src/org/pentaho/metadata/XmiParserIT.java

Integration test coverage change:
============
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * Complexity Change :  + 5.26%
 * Instruction Change :  + 2.78%
 * Line Change :  + 3.95%
 * Method Change :  + 6.90%

org.pentaho.metadata.util.XmiParser:
 * Branch Change :  + .07%
 * Complexity Change :  + .11%
 * Instruction Change :  + .03%
 * Line Change :  + .03%

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/src/org/pentaho/metadata/util/XmiParser.java

1. Message: Must have at least one statement. at Line: 930 Column: 45
2. Message: Must have at least one statement. at Line: 987 Column: 101
3. Message: Must have at least one statement. at Line: 1,732 Column: 68
4. Message: Must have at least one statement. at Line: 1,927 Column: 20

File /home/buildguy/project/test-src/org/pentaho/metadata/XmiParserIT.java

1. Message: Using a static member import should be avoided - org.pentaho.metadata.util.Util.validateId. at Line: 23

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/olap/OlapHierarchyLevel.java
  src/org/pentaho/metadata/util/XmiParser.java
  test-src/org/pentaho/metadata/XmiParserIT.java

Integration test coverage change:
============
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * Complexity Change :  + 5.26%
 * Instruction Change :  + 2.78%
 * Line Change :  + 3.95%
 * Method Change :  + 6.90%

org.pentaho.metadata.util.XmiParser:
 * Branch Change :  + .07%
 * Complexity Change :  + .11%
 * Instruction Change :  + .03%
 * Line Change :  + .03%

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/src/org/pentaho/metadata/util/XmiParser.java

1. Message: Must have at least one statement. at Line: 930 Column: 45
2. Message: Must have at least one statement. at Line: 987 Column: 101
3. Message: Must have at least one statement. at Line: 1,732 Column: 68
4. Message: Must have at least one statement. at Line: 1,927 Column: 20

File /home/buildguy/project/test-src/org/pentaho/metadata/XmiParserIT.java

1. Message: Using a static member import should be avoided - org.pentaho.metadata.util.Util.validateId. at Line: 23

**Comment by kurtwalker** [comment]
@rfellows @DFieldFL @pminutillo please review.  Checkstyle issues were pre-existing and have comments for ignoring.

**Pull request merged**
