### PR TITLE
[BISERVER-13338] - Data source domain object mutation while re-parsing

### PR DESCRIPTION
**Pull request by YuryBY**

### CODE REVIEW

**Comment by YuryBY** [comment]
@wseyler, @mbatchelor, @dkincade, could you please take a look?

**Comment by YuryBY** [comment]
@wseyler, @mbatchelor, @dkincade, any updates?

**Comment by dkincade** [comment]
We are focused on 8.0.0.0 right now and this does not look like it is included. We will return to this before long.

**Comment by mchen-len-son** [comment]
@wseyler, @mbatchelor, @dkincade can you please take a look?
thanks.

**Comment by YuryBY** [comment]
@wseyler, @mbatchelor, @dkincade, @pamval, any updates?

**Pull request merged**
