### PR TITLE
PDB-1844 - PIR report in dashboard widget displays fields which were …

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
…deleted from datasource.

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@tmorgner @pentaho-nbaker 
Please review.

**Comment by Aliaksandr-Kastenka** [comment]
@bennychow 
Please review.

**Comment by tmorgner** [comment]
I dont think your fix is more than just a work around for a broken or inconsistent Metadata model. As your case involves editing the metadata model, I suspect the deleting of columns does not correctly delete the logical column from the model.

Your fix only makes sense if there is a discrepancy in the result of your columnId to column lookup. There are two paths on how you get a column from a column id in that method:

(a) you have a view node, and the view can be resolved to a category (Lines 445-449). That category is then used to lookup the column (line 452).

(b) you have no view node. The column-id comes directly from the "column" tag. The corresponding column is found by traversing all logical tables. (Line 454)

The symptom you are fixing seems to be that you have a non-null column at this position, but the correct result should have been a null-value in the column variable. 

That is why in line 456 you added a second test to search for the column by Id in all defined categories. 

If you have a non-null column, and your second test returns a column after searching through all the categories known, then that means that there is a mismatch between the categories and their known logical columns and the physical tables and their logical columns. 

As a loglcal column can exist without a category (but wont be accessible to the user at that point), you should not search for columns by going through the physical tables. Change Line 454 from "findLogicalColumn" to "findLogicalColumnInCategories"). Then you dont need to cross-check your result in line 456 a second time.

I would also love to see a unit test for this. The dependencies for this method should be easy to mock, as you work against interfaces here. So please add a test as well to proof you fixed the code correctly.

**Comment by Aliaksandr-Kastenka** [comment]
@tmorgner 
Please review.

**Comment by tmorgner** [comment]
Now that looks good

**Pull request merged**
