### PR TITLE
[BACKLOG-5768] Add hidden attribute to Measure and Level

### PR DESCRIPTION
**Pull request by bytekast**

### CODE REVIEW

**Comment by bytekast** [comment]
@bennychow @rfellows @kurtwalker - please review

**Comment by rfellows** [comment]
Looks good to me

**Comment by bennychow** [comment]
Looks good to me too.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/olap/OlapHierarchyLevel.java
  src/org/pentaho/metadata/model/olap/OlapMeasure.java
  src/org/pentaho/metadata/util/MondrianModelExporter.java
  src/org/pentaho/metadata/util/XmiParser.java
  test-src/org/pentaho/metadata/MondrianModelExporterTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File src/org/pentaho/metadata/util/XmiParser.java
1. Message: File length is 2,087 lines (max allowed is 2,000). at Line: 1 Column: None
2. Message: 'if' is not followed by whitespace. at Line: 1164 Column: 9
3. Message: ')' is not preceded with whitespace. at Line: 1514 Column: 65
4. Message: '(' is not followed by whitespace. at Line: 1516 Column: 60
5. Message: ')' is not preceded with whitespace. at Line: 1516 Column: 64
6. Message: ')' is not preceded with whitespace. at Line: 1518 Column: 85
7. Message: '(' is not followed by whitespace. at Line: 1520 Column: 103
8. Message: ')' is not preceded with whitespace. at Line: 1520 Column: 107
9. Message: '(' is not followed by whitespace. at Line: 1523 Column: 20
10. Message: ')' is not preceded with whitespace. at Line: 1523 Column: 41
11. Message: '(' is not followed by whitespace. at Line: 1525 Column: 21
12. Message: ')' is not preceded with whitespace. at Line: 1525 Column: 62
13. Message: 'if' construct must use '{}'s. at Line: 1525 Column: None
14. Message: Line has trailing spaces. at Line: 1532 Column: None
15. Message: '(' is not followed by whitespace. at Line: 1628 Column: 20
16. Message: ')' is not preceded with whitespace. at Line: 1628 Column: 26
17. Message: Must have at least one statement. at Line: 1679 Column: 68
18. Message: '?' should be on a new line. at Line: 1788 Column: 96
19. Message: '?' should be on a new line. at Line: 1839 Column: 82
20. Message: Must have at least one statement. at Line: 1858 Column: 20
21. Message: '(' is not followed by whitespace. at Line: 2032 Column: 78
22. Message: ')' is not preceded with whitespace. at Line: 2032 Column: 94
23. Message: '(' is not followed by whitespace. at Line: 2042 Column: 9
24. Message: ')' is not preceded with whitespace. at Line: 2042 Column: 31
25. Message: Line has trailing spaces. at Line: 302 Column: None
26. Message: Line has trailing spaces. at Line: 379 Column: None
27. Message: '(' is not followed by whitespace. at Line: 383 Column: 13
28. Message: ')' is not preceded with whitespace. at Line: 383 Column: 26
29. Message: '(' is not followed by whitespace. at Line: 385 Column: 25
30. Message: ')' is not preceded with whitespace. at Line: 385 Column: 34
31. Message: '(' is not followed by whitespace. at Line: 386 Column: 16
32. Message: ')' is not preceded with whitespace. at Line: 386 Column: 37
33. Message: '(' is not followed by whitespace. at Line: 387 Column: 17
34. Message: ')' is not preceded with whitespace. at Line: 387 Column: 102
35. Message: '(' is not followed by whitespace. at Line: 388 Column: 29
36. Message: ')' is not preceded with whitespace. at Line: 388 Column: 37
37. Message: ')' is not preceded with whitespace. at Line: 389 Column: 76
38. Message: '(' is not followed by whitespace. at Line: 390 Column: 62
39. Message: ')' is not preceded with whitespace. at Line: 390 Column: 93
40. Message: '(' is not followed by whitespace. at Line: 391 Column: 29
41. Message: ')' is not preceded with whitespace. at Line: 391 Column: 38
42. Message: '(' is not followed by whitespace. at Line: 394 Column: 25
43. Message: ')' is not preceded with whitespace. at Line: 394 Column: 35
44. Message: Line has trailing spaces. at Line: 397 Column: None
45. Message: ';' is not followed by whitespace. at Line: 438 Column: 98
46. Message: ';' is not followed by whitespace. at Line: 442 Column: 101
47. Message: ';' is not followed by whitespace. at Line: 446 Column: 97
48. Message: ';' is not followed by whitespace. at Line: 450 Column: 100
49. Message: ';' is not followed by whitespace. at Line: 453 Column: 117
50. Message: ';' is not followed by whitespace. at Line: 455 Column: 90
51. Message: ';' is not followed by whitespace. at Line: 459 Column: 101
52. Message: ';' is not followed by whitespace. at Line: 463 Column: 93
53. Message: 'if' is not followed by whitespace. at Line: 601 Column: 19
54. Message: '{' is not preceded with whitespace. at Line: 601 Column: 41
55. Message: ')' is not preceded with whitespace. at Line: 603 Column: 119
56. Message: 'if' is not followed by whitespace. at Line: 749 Column: 23
57. Message: '{' is not preceded with whitespace. at Line: 749 Column: 43
58. Message: Must have at least one statement. at Line: 902 Column: 45
59. Message: Must have at least one statement. at Line: 959 Column: 101


License header violations:
==========================

1. test-src/org/pentaho/metadata/MondrianModelExporterTest.java








Unit test coverage change:
============
org.pentaho.metadata.query.model.util.CsvDataTypeEvaluator.CountItemsList:
 * branchPercentCoverageChange : +12.50%
 * complexityPercentCoverageChange : +12.50%
    
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * instructionPercentCoverageChange : +2.29%
 * linePercentCoverageChange : +3.05%
 * complexityPercentCoverageChange : +3.43%
 * methodPercentCoverageChange : +3.85%
    
org.pentaho.metadata.model.olap.OlapMeasure:
 * instructionPercentCoverageChange : +10.04%
 * linePercentCoverageChange : +8.65%
 * complexityPercentCoverageChange : +9.52%
 * methodPercentCoverageChange : +9.52%
    
org.pentaho.metadata.util.MondrianModelExporter:
 * instructionPercentCoverageChange : +0.20%
 * branchPercentCoverageChange : +1.09%
 * linePercentCoverageChange : +0.44%
 * complexityPercentCoverageChange : +0.95%
    
Integration test coverage change:
============
org.pentaho.metadata.util.XmiParser:
 * instructionPercentCoverageChange :**-0.72%**
 * branchPercentCoverageChange :**-0.44%**
 * linePercentCoverageChange :**-0.13%**
 * complexityPercentCoverageChange :**-0.89%**
    
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * instructionPercentCoverageChange : +2.10%
 * linePercentCoverageChange : +2.70%
 * complexityPercentCoverageChange : +3.27%
 * methodPercentCoverageChange : +3.26%
    
org.pentaho.metadata.model.olap.OlapMeasure:
 * instructionPercentCoverageChange : +8.54%
 * linePercentCoverageChange : +7.21%
 * complexityPercentCoverageChange : +6.35%
 * methodPercentCoverageChange : +6.35%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/olap/OlapHierarchyLevel.java
  src/org/pentaho/metadata/model/olap/OlapMeasure.java
  src/org/pentaho/metadata/util/MondrianModelExporter.java
  src/org/pentaho/metadata/util/XmiParser.java
  test-src/org/pentaho/metadata/MondrianModelExporterTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File src/org/pentaho/metadata/util/XmiParser.java
1. Message: File length is 2,152 lines (max allowed is 2,000). at Line: 1 Column: None
2. Message: 'if' construct must use '{}'s. at Line: 1569 Column: None
3. Message: Must have at least one statement. at Line: 1725 Column: 68
4. Message: '?' should be on a new line. at Line: 1842 Column: 96
5. Message: '?' should be on a new line. at Line: 1899 Column: 82
6. Message: Must have at least one statement. at Line: 1918 Column: 20
7. Message: 'getKeyValue' have incorrect indentation level 2, expected level should be 4. at Line: 2139 Column: None
8. Message: ';' is not followed by whitespace. at Line: 443 Column: 98
9. Message: ';' is not followed by whitespace. at Line: 447 Column: 101
10. Message: ';' is not followed by whitespace. at Line: 451 Column: 97
11. Message: ';' is not followed by whitespace. at Line: 455 Column: 100
12. Message: ';' is not followed by whitespace. at Line: 459 Column: 39
13. Message: ';' is not followed by whitespace. at Line: 461 Column: 90
14. Message: ';' is not followed by whitespace. at Line: 465 Column: 101
15. Message: ';' is not followed by whitespace. at Line: 469 Column: 93
16. Message: Must have at least one statement. at Line: 924 Column: 45
17. Message: Must have at least one statement. at Line: 981 Column: 101









Unit test coverage change:
============
org.pentaho.metadata.query.model.util.CsvDataTypeEvaluator.CountItemsList:
 * branchPercentCoverageChange : +12.50%
 * complexityPercentCoverageChange : +12.50%
    
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * instructionPercentCoverageChange : +2.29%
 * linePercentCoverageChange : +3.05%
 * complexityPercentCoverageChange : +3.43%
 * methodPercentCoverageChange : +3.85%
    
org.pentaho.metadata.model.olap.OlapMeasure:
 * instructionPercentCoverageChange : +10.04%
 * linePercentCoverageChange : +8.65%
 * complexityPercentCoverageChange : +9.52%
 * methodPercentCoverageChange : +9.52%
    
org.pentaho.metadata.util.MondrianModelExporter:
 * instructionPercentCoverageChange : +0.20%
 * branchPercentCoverageChange : +1.09%
 * linePercentCoverageChange : +0.44%
 * complexityPercentCoverageChange : +0.95%
    
Integration test coverage change:
============
org.pentaho.metadata.query.model.util.CsvDataTypeEvaluator.CountItemsList:
 * branchPercentCoverageChange : +12.50%
 * complexityPercentCoverageChange : +12.50%
    
org.pentaho.metadata.util.XmiParser:
 * instructionPercentCoverageChange :**-0.72%**
 * branchPercentCoverageChange :**-0.44%**
 * linePercentCoverageChange :**-0.13%**
 * complexityPercentCoverageChange :**-0.89%**
    
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * instructionPercentCoverageChange : +2.10%
 * linePercentCoverageChange : +2.70%
 * complexityPercentCoverageChange : +3.27%
 * methodPercentCoverageChange : +3.26%
    
org.pentaho.metadata.model.olap.OlapMeasure:
 * instructionPercentCoverageChange : +8.54%
 * linePercentCoverageChange : +7.21%
 * complexityPercentCoverageChange : +6.35%
 * methodPercentCoverageChange : +6.35%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/olap/OlapHierarchyLevel.java
  src/org/pentaho/metadata/model/olap/OlapMeasure.java
  src/org/pentaho/metadata/util/MondrianModelExporter.java
  src/org/pentaho/metadata/util/XmiParser.java
  test-src/org/pentaho/metadata/MondrianModelExporterTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File src/org/pentaho/metadata/util/XmiParser.java
1. Message: File length is 2,153 lines (max allowed is 2,000). at Line: 1 Column: None
2. Message: Must have at least one statement. at Line: 1726 Column: 68
3. Message: Must have at least one statement. at Line: 1919 Column: 20
4. Message: Must have at least one statement. at Line: 924 Column: 45
5. Message: Must have at least one statement. at Line: 981 Column: 101









Unit test coverage change:
============
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * instructionPercentCoverageChange : +2.29%
 * linePercentCoverageChange : +3.05%
 * complexityPercentCoverageChange : +3.43%
 * methodPercentCoverageChange : +3.85%
    
org.pentaho.metadata.model.olap.OlapMeasure:
 * instructionPercentCoverageChange : +10.04%
 * linePercentCoverageChange : +8.65%
 * complexityPercentCoverageChange : +9.52%
 * methodPercentCoverageChange : +9.52%
    
org.pentaho.metadata.util.MondrianModelExporter:
 * instructionPercentCoverageChange : +0.20%
 * branchPercentCoverageChange : +1.09%
 * linePercentCoverageChange : +0.44%
 * complexityPercentCoverageChange : +0.95%
    
Integration test coverage change:
============
org.pentaho.metadata.util.XmiParser:
 * instructionPercentCoverageChange :**-0.72%**
 * branchPercentCoverageChange :**-0.44%**
 * linePercentCoverageChange :**-0.13%**
 * complexityPercentCoverageChange :**-0.89%**
    
org.pentaho.metadata.model.olap.OlapHierarchyLevel:
 * instructionPercentCoverageChange : +2.10%
 * linePercentCoverageChange : +2.70%
 * complexityPercentCoverageChange : +3.27%
 * methodPercentCoverageChange : +3.26%
    
org.pentaho.metadata.model.olap.OlapMeasure:
 * instructionPercentCoverageChange : +8.54%
 * linePercentCoverageChange : +7.21%
 * complexityPercentCoverageChange : +6.35%
 * methodPercentCoverageChange : +6.35%

**Pull request merged**
