### PR TITLE
[PDB-1427] Default date formats in dashboard and PIR are not same

### PR DESCRIPTION
**Pull request by SergeyTravin**

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@pminutillo, @bytekast, @akhayrutdinov  could you  review please?
It should be merged after
https://github.com/pentaho/pentaho-connections/pull/10

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/concept/types/DataType.java
  src/org/pentaho/metadata/model/concept/util/DataFormatter.java
  src/org/pentaho/metadata/query/model/util/QueryModelMetaData.java
  test-src/org/pentaho/metadata/libformula/FunctionsTest.java
  test-src/org/pentaho/metadata/model/concept/types/LocalizedStringTest.java
  test-src/org/pentaho/metadata/model/concept/util/DataFormatterTest.java
  test-src/org/pentaho/metadata/query/model/util/QueryModelMetaDataTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File test-src/org/pentaho/metadata/libformula/FunctionsTest.java
1. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 109 Column: 5
2. Message: 'catch' is not followed by whitespace. at Line: 110 Column: 10
3. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 126 Column: 5
4. Message: 'catch' is not followed by whitespace. at Line: 127 Column: 10
5. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 142 Column: 5
6. Message: 'catch' is not followed by whitespace. at Line: 143 Column: 10
7. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 159 Column: 5
8. Message: 'catch' is not followed by whitespace. at Line: 160 Column: 10
9. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 178 Column: 5
10. Message: 'catch' is not followed by whitespace. at Line: 179 Column: 10
11. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 197 Column: 5
12. Message: 'catch' is not followed by whitespace. at Line: 198 Column: 10
13. Message: Line has trailing spaces at Line: 214 Column: None
14. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 217 Column: 5
15. Message: 'catch' is not followed by whitespace. at Line: 218 Column: 10
16. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 237 Column: 5
17. Message: 'catch' is not followed by whitespace. at Line: 238 Column: 10
18. Message: '(' is preceded with whitespace. at Line: 247 Column: 34
19. Message: Line has trailing spaces at Line: 255 Column: None
20. Message: Line has trailing spaces at Line: 260 Column: None
21. Message: Line has trailing spaces at Line: 269 Column: None
22. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 43 Column: 5
23. Message: 'catch' is not followed by whitespace. at Line: 44 Column: 10
24. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 60 Column: 5
25. Message: 'catch' is not followed by whitespace. at Line: 61 Column: 10
26. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 76 Column: 5
27. Message: 'catch' is not followed by whitespace. at Line: 77 Column: 10
28. Message: '}' at column 5 should be on the same line as the next part of a multi-block statement. at Line: 93 Column: 5
29. Message: 'catch' is not followed by whitespace. at Line: 94 Column: 10









Unit test coverage change:
============
org.pentaho.metadata.model.concept.util.DataFormatter.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :86.89%
    
org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * instructionPercentCoverageChange :**-3.91%**
 * linePercentCoverageChange :**-6.84%**
 * complexityPercentCoverageChange :**-3.33%**
 * methodPercentCoverageChange :**-25.00%**
    
org.pentaho.metadata.model.concept.util.DataFormatter:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :95.00%
 * methodPercentCoverage :75.00%
 * complexityPercentCoverage :88.89%
 * instructionPercentCoverage :96.77%
    
Integration test coverage change:
============
org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * instructionPercentCoverageChange :**-3.14%**
 * linePercentCoverageChange :**-5.01%**
 * complexityPercentCoverageChange :**-3.33%**
 * methodPercentCoverageChange :**-25.00%**

**Comment by SergeyTravin** [comment]
@pminutillo, @bytekast,  @pamval, could you please restart WM?

**Comment by pamval** [comment]
@pedrofvteixeira can you please start wingman for this one ?

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/415)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/concept/types/DataType.java
  src/org/pentaho/metadata/model/concept/util/DataFormatter.java
  src/org/pentaho/metadata/query/model/util/QueryModelMetaData.java
  test-src/org/pentaho/metadata/libformula/FunctionsTest.java
  test-src/org/pentaho/metadata/model/concept/types/LocalizedStringTest.java
  test-src/org/pentaho/metadata/model/concept/util/DataFormatterTest.java
  test-src/org/pentaho/metadata/query/model/util/QueryModelMetaDataTest.java










Unit test coverage change:
============
org.pentaho.metadata.model.concept.util.DataFormatter.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :86.89%
    
org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * instructionPercentCoverageChange : +10.86%
 * branchPercentCoverageChange : +14.29%
 * linePercentCoverageChange : +9.13%
 * complexityPercentCoverageChange : +23.81%
 * methodPercentCoverageChange : +25.00%
    
org.pentaho.metadata.model.concept.util.DataFormatter:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :95.00%
 * methodPercentCoverage :75.00%
 * complexityPercentCoverage :88.89%
 * instructionPercentCoverage :96.77%
    
Integration test coverage change:
============
org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * instructionPercentCoverageChange :**-6.22%**
 * linePercentCoverageChange :**-7.95%**
 * complexityPercentCoverageChange :**-4.76%**
 * methodPercentCoverageChange :**-32.14%**

**Comment by SergeyTravin** [comment]
@akhayrutdinov could you review please, wingman was finished.

**Comment by akhayrutdinov** [comment]
Also, please rename the PR to be equal to others, but not `Pdb 1427`

**Comment by SergeyTravin** [comment]
@akhayrutdinov, Notes was fixed, it would be nice if you have a chance to review it again. Thanks!

**Comment by akhayrutdinov** [comment]
@pamval, @pedrofvteixeira, run WM for this PR please

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/441)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/metadata/model/concept/types/DataType.java
  src/org/pentaho/metadata/model/concept/util/DataFormatter.java
  src/org/pentaho/metadata/query/model/util/QueryModelMetaData.java
  test-src/org/pentaho/metadata/libformula/FunctionsTest.java
  test-src/org/pentaho/metadata/model/concept/types/LocalizedStringTest.java
  test-src/org/pentaho/metadata/model/concept/util/DataFormatterTest.java
  test-src/org/pentaho/metadata/query/model/util/QueryModelMetaDataTest.java










Unit test coverage change:
============
org.pentaho.metadata.model.concept.util.DataFormatter.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :86.89%
    
org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * instructionPercentCoverageChange : +10.86%
 * branchPercentCoverageChange : +14.29%
 * linePercentCoverageChange : +9.13%
 * complexityPercentCoverageChange : +23.81%
 * methodPercentCoverageChange : +25.00%
    
org.pentaho.metadata.model.concept.util.DataFormatter:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :71.43%
 * methodPercentCoverage :75.00%
 * complexityPercentCoverage :83.33%
 * instructionPercentCoverage :73.77%
    
Integration test coverage change:
============
org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * instructionPercentCoverageChange :**-6.22%**
 * linePercentCoverageChange :**-7.95%**
 * complexityPercentCoverageChange :**-4.76%**
 * methodPercentCoverageChange :**-32.14%**

**Comment by akhayrutdinov** [comment]
@pamval, I don't have write permission for this repository. I'm OK with the changes, mind merging it please?
As for `methodPercentCoverageChange :-32.14%`, that simply happened because there are few methods in the class, and adding a constructor and a getter is significant for that amount.

**Comment by lucboudreau** [comment]
@akhayrutdinov Then why not test the constructor and the getters?

**Pull request merged**
