### PR TITLE
[PDI-19906] - Google BigQuery Simba driver version 1.3.3.1004 in Pentaho

### PR DESCRIPTION
**Pull request by bcostahitachivantara**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 7m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **111**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/metadata/job/PR-233/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **111**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/metadata/job/PR-233/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
