### PR TITLE
[TEST] Fixing failing IT tests.

### PR DESCRIPTION
**Pull request by mkambol**
A refactor of SelectValuesMeta broke a
InlineEtlQueryExecutor, which was using
a getter as a setter (ie changing a property
backed by an array).

### CODE REVIEW

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/54/

**Comment by lucboudreau** [comment]
Error building command: /home/devuser/docker-build/assembly/build/assembly-0.0.1/source/pentaho-metadata-base-88-4f2a46f1-a9c6-4bba-ad76-d81536f60baf/pom.xml (No such file or directory)

**Comment by lucboudreau** [comment]
Yeah, @brosander made a change yesterday and now Wingman thinks everything is a maven project. Please ping him.

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-ant-cmd/1/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  src/org/pentaho/metadata/query/impl/ietl/InlineEtlQueryExecutor.java

Newly Fixed Tests:
======================
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecution: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<5> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecution(InlineEtlModelGeneratorIT.java:149)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionAllAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionAllAggregations(InlineEtlModelGeneratorIT.java:615)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregations(InlineEtlModelGeneratorIT.java:468)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregationsAndConstraints: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<2> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregationsAndConstraints(InlineEtlModelGeneratorIT.java:568)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithConstraints: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithConstraints(InlineEtlModelGeneratorIT.java:250)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithDifferentAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithDifferentAggregations(InlineEtlModelGeneratorIT.java:516)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithFormulaFunctions: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithFormulaFunctions(InlineEtlModelGeneratorIT.java:366)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithOrder: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<5> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithOrder(InlineEtlModelGeneratorIT.java:196)

```

Integration test coverage change:
============
org.pentaho.metadata.query.impl.ietl.InlineEtlQueryExecutor:
 * Branch Change :  + 8.59%
 * Complexity Change :  + 10.28%
 * Instruction Change :  + 4.54%
 * Line Change :  + 6.19%

org.pentaho.metadata.query.impl.ietl.InlineEtlQueryExecutor.InlineEtlRowListener:
 * Branch Change :  + 38.46%
 * Complexity Change :  + 36.36%
 * Instruction Change :  + 40.00%
 * Line Change :  + 40.35%
 * Method Change :  + 50.00%

org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * Branch Change :  + 3.57%
 * Complexity Change :  + 4.76%
 * Instruction Change :  + 5.63%
 * Line Change :  + 1.82%

**Comment by mkambol** [comment]
@hudak 
Different song, same tune.

**Comment by brosander** [comment]
Testing auto ant/mvn detection

**Comment by brosander** [comment]
Error building command: /home/bryan/platform-codebase/docker-build/assembly/build/assembly-0.0.1/source/pentaho-metadata-base-88-ed0825e8-a241-4773-a478-5daca839a739/pom.xml (No such file or directory)

**Comment by brosander** [comment]
Testing auto ant/mvn detection

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  src/org/pentaho/metadata/query/impl/ietl/InlineEtlQueryExecutor.java

Newly Fixed Tests:
======================
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecution: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<5> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecution(InlineEtlModelGeneratorIT.java:149)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionAllAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionAllAggregations(InlineEtlModelGeneratorIT.java:615)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregations(InlineEtlModelGeneratorIT.java:468)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregationsAndConstraints: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<2> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregationsAndConstraints(InlineEtlModelGeneratorIT.java:568)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithConstraints: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithConstraints(InlineEtlModelGeneratorIT.java:250)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithDifferentAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithDifferentAggregations(InlineEtlModelGeneratorIT.java:516)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithFormulaFunctions: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithFormulaFunctions(InlineEtlModelGeneratorIT.java:366)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithOrder: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<5> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithOrder(InlineEtlModelGeneratorIT.java:196)

```

Integration test coverage change:
============
org.pentaho.metadata.query.impl.ietl.InlineEtlQueryExecutor:
 * Branch Change :  + 8.59%
 * Complexity Change :  + 10.28%
 * Instruction Change :  + 4.54%
 * Line Change :  + 6.19%

org.pentaho.metadata.query.impl.ietl.InlineEtlQueryExecutor.InlineEtlRowListener:
 * Branch Change :  + 38.46%
 * Complexity Change :  + 36.36%
 * Instruction Change :  + 40.00%
 * Line Change :  + 40.35%
 * Method Change :  + 50.00%

org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * Branch Change :  + 3.57%
 * Complexity Change :  + 4.76%
 * Instruction Change :  + 5.63%
 * Line Change :  + 1.82%

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/56/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  src/org/pentaho/metadata/query/impl/ietl/InlineEtlQueryExecutor.java

Newly Fixed Tests:
======================
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecution: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<5> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecution(InlineEtlModelGeneratorIT.java:149)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionAllAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionAllAggregations(InlineEtlModelGeneratorIT.java:615)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregations(InlineEtlModelGeneratorIT.java:468)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregationsAndConstraints: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<2> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithAggregationsAndConstraints(InlineEtlModelGeneratorIT.java:568)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithConstraints: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithConstraints(InlineEtlModelGeneratorIT.java:250)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithDifferentAggregations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithDifferentAggregations(InlineEtlModelGeneratorIT.java:516)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithFormulaFunctions: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithFormulaFunctions(InlineEtlModelGeneratorIT.java:366)

```
org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithOrder: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<5> but was:<0>
	at org.pentaho.metadata.InlineEtlModelGeneratorIT.testQueryExecutionWithOrder(InlineEtlModelGeneratorIT.java:196)

```

Integration test coverage change:
============
org.pentaho.metadata.query.impl.ietl.InlineEtlQueryExecutor:
 * Branch Change :  + 8.59%
 * Complexity Change :  + 10.28%
 * Instruction Change :  + 4.54%
 * Line Change :  + 6.19%

org.pentaho.metadata.query.impl.ietl.InlineEtlQueryExecutor.InlineEtlRowListener:
 * Branch Change :  + 38.46%
 * Complexity Change :  + 36.36%
 * Instruction Change :  + 40.00%
 * Line Change :  + 40.35%
 * Method Change :  + 50.00%

org.pentaho.metadata.query.model.util.QueryModelMetaData:
 * Branch Change :  + 3.57%
 * Complexity Change :  + 4.76%
 * Instruction Change :  + 5.63%
 * Line Change :  + 1.82%

**Comment by brosander** [comment]
@lucboudreau we should be able to guess build tools now

**Pull request merged**
