### PR TITLE
[SP-2768] Backport of BISERVER-13159 - Upgrade issue from 5.1 to 5.4 …

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[SP-2768] Backport of BISERVER-13159 - Upgrade issue from 5.1 to 5.4 when SQL datasource created via Data Access Wizard has Japanese Columns in it. (6.1 Suite)

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
backport of #102

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @CodeOnCoffee, @pamval,  @mchen-len-son please review

**Comment by lucboudreau** [comment]
Please check if you can fix these failures. Thanks.

**Comment by stanislau-strelchanka** [comment]
@lucboudreau update pr, please rerun wingman

**Comment by mchen-len-son** [comment]
I don't see a quick solution for the failing tests. The test data has to be updated somehow.

@pamval can you please take a look? I don't have rights to merge it. I checked - everything, except specified failing tests, is ok.

**Pull request merged**
